# Header
menu:
  Home: /
  Archives: /archives

# links with icon in the left-column bar
subnav:
  # github: "#"
  # mail: "#"
  # rss: "#"
  # zhihu: "#"
  # weibo: "#"
  # douban: "#"
  # facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

# it is the relative path of the .xml file, the default path is in the source directory
rss:

# you can modify the value of excerpt_link to what you like
excerpt_link: learn more
fancybox: true
mathjax: true

# open the animation effect, true recommended
animate: true

# whether to open the link in the new window
open_in_new: false

# 百度统计、谷歌统计
# baidu_tongji: true
# google_analytics: true

favicon: /img/favicon.ico

# your avatar's url
avatar: 



#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: your duoshuo id

# 是否开启云标签
tagcloud: true

# 是否开启文章阅读量
leancloud_visitors:
  enable: false
  app_id: your_app_id
  app_key: your_app_key

# 是否开启友情链接
# 不开启
# friends: false
# 开启
friends:
  github: https://github.com/
# 是否开启“关于我”
aboutme: I'm an engineer.
